language: python
python:
  - '2.7'
sudo: required
dist: trusty
install:
  - source cfg4dev
  - pip install --requirement tests/load/requirements.txt
  - pip install coveralls
  - nvm install 4.1.0
  - npm i -g raml2md
  - npm i -g raml2html
script:
  - pep8
  - flake8
  - tor_async_util_nosetests.py --with-coverage --cover-branches --cover-erase --cover-package ecs
  - coveralls || true
  - tests/load/run_load_test.sh -v tests/load/load-test-config-for-travis.json
  - python setup.py sdist --formats=gztar
  - ./api_docs/build-api-docs.sh -t
  - if [ "$TRAVIS_BRANCH" == "master" ] || [ "$TRAVIS_TAG" != "" ]; then ./dockerfiles/build-docker-images.sh -v -t "$TRAVIS_TAG" ./dist/ecs-*.*.*.tar.gz ./api_docs/api_docs.tar $DOCKER_USERNAME $DOCKER_PASSWORD; fi
