#%RAML 0.8

title: Ephemeral Container Service (ECS) (%ECS_VERSION% / %ECS_API_VERSION%)
version: v99.999
documentation:
  - title: Overview
    content: |
      The Ephemeral Container Service (ECS) was born out of
      the [Cloudfeaster](https://github.com/simonsdave/cloudfeaster.git) project.
      [Docker](https://www.docker.com/) makes it easy to package
      short lived (aka ephemeral) tasks in a docker image and run
      those tasks using
      the [Docker Remote API](https://docs.docker.com/engine/reference/api/docker_remote_api/).
      ECS adds a service on top these building blocks that allows ephemeral tasks
      to be run on a cluster of [CoreOS](https://coreos.com/) machines using a RESTful API.

  - title: Security
    content: |
      ##### In-transit
      All communication with an ECS deployment is done over SSL/TLS.
      The ECS runs on a cluster of [CoreOS](https://coreos.com/) machines
      with a layer 5 (TCP) load balancer running in front of the cluster.
      Layer 5 load balancing is required because [nginx](http://nginx.org)
      is used to terminate SSL/TLS on each node in the cluster.

      Note - ECS nodes host both the api and docs domains on a single IP
      with 2 distinct SSL/TLS certificates. Clients making requests into an ECS
      deployment should support
      [SNI](https://en.wikipedia.org/wiki/Server_Name_Indication) to ensure
      the correct SSL/TLS certificate is used.

      Note - SSL/TLS configuration derived from
      [Mozilla's Security/Server Side TLS](https://wiki.mozilla.org/Security/Server_Side_TLS)
      using ```nginx``` and ```modern``` settings.
      This may have client implications.
      For example, only ```TLSv1.2``` is supported so older clients
      may struggle to establish an SSL/TLS connection.
      To verify/evaluate the SSL/TLS configuration for an ECS
      deployment try using [Qualys' SSL Server Test](https://www.ssllabs.com/ssltest/).
      Below is a sample Qualys report for ```api.ecs.cloudfeaster.com```.

      <a href="static/qualys-ssl-labs-api-ecs-cloudfeaster-com-assessment.pdf">
        <img src="static/qualys-ssl-labs-api-ecs-cloudfeaster-com-assessment.png" align="middle" height="412" width="712"/>
      </a>

      FYI - [here's](https://www.ssllabs.com/downloads/SSL_Server_Rating_Guide.pdf)
      a paper which describes how Qualys calculates its rating of your SSL/TLS configuration.

      ##### At-rest
      The ECS does not persist any data.

      ##### Authentication
      All requests (except API doc requests) into an ECS deployment
      must pass BASIC authentication against a key & secret. Keys & secrets
      are configured when a deployment is created.
      ```ecsctl.sh``` is typically used to generate keys & secrets.
      Keys are [UUIDs](https://docs.python.org/2/library/uuid.html#uuid.uuid4).
      Secrets are are 128-bit random numbers generated using
      [/dev/urandom](http://en.wikipedia.org/wiki//dev/urandom)
      (via Python's [os.urandom()](https://docs.python.org/2/library/os.html#os-miscfunc)).
      After secrets are generated, only a
      hashed version of the secrets is written to disk.

      ##### Authorization
      The ECS is intended to be used a low level, utility service
      sitting behind a higher level abstraction that implements authorization.
      As such, as soon as a requestor is authenticated they are able to access
      any of ECS' endpoints.

      ##### Firewalls
      Every ECS deployment employs 2 different types of firewalls - network and node.
      
      ##### Network Firewall
      All nodes in an ECS cluster sit on a single network.
      [Firewall rules](https://cloud.google.com/compute/docs/networking#firewalls)
      define what traffic is permitted into this network.
      Requests into an deployment are load balanced across ECS cluster nodes using
      [Google Compute Engine's (layer 5) Network Load Balancing](https://cloud.google.com/compute/docs/load-balancing-and-autoscaling#network_load_balancing).

      <a href="https://nmap.org">nmap</a> can also be used to validate the
      configuration of the firewall rules and load balancer.
      Below is sample ```nmap``` output.

      ```bash
      >nmap api.ecs.cloudfeaster.com

      Starting Nmap 6.40 ( http://nmap.org ) at 2016-03-27 07:33 EST
      Nmap scan report for api.ecs.cloudfeaster.com (104.197.213.254)
      Host is up (0.082s latency).
      rDNS record for 104.197.213.254: 254.213.197.104.bc.googleusercontent.com
      Not shown: 998 filtered ports
      PORT    STATE SERVICE
      80/tcp  open  http
      443/tcp open  https

      Nmap done: 1 IP address (1 host up) scanned in 12.14 seconds
      >
      ```

      ##### Node Firewall
      Each node in an ECS cluster uses a combination of 
      <a href="https://wiki.ubuntu.com/UncomplicatedFirewall">iptables & netfilter</a>
      as a firewall.
      <a href="https://coreos.com/os/docs/latest/cloud-config.html">CoreOS's cloud-config</a>
      and the ```iptables-restore.service``` unit are used to configure the firewall
      when a node boots.
      <a href="https://nmap.org">nmap</a> can be used to verify
      <a href="https://wiki.ubuntu.com/UncomplicatedFirewall">iptables & netfilter</a>
      are correctly configured.
      Below is the output from running <a href="https://nmap.org">nmap</a>
      against an ECS node with an external IP of ```104.154.102.140```.

      ```bash
      >nmap 23.251.145.126

      Starting Nmap 6.40 ( http://nmap.org ) at 2016-03-27 07:42 EST
      Nmap scan report for 126.145.251.23.bc.googleusercontent.com (23.251.145.126)
      Host is up (0.044s latency).
      Not shown: 997 filtered ports
      PORT    STATE SERVICE
      22/tcp  open  ssh
      80/tcp  open  http
      443/tcp open  https

      Nmap done: 1 IP address (1 host up) scanned in 6.71 seconds
      >
      ```

  - title: Request and Rate Limiting
    content: |
      Each node in an ECS cluster implements a set of request and rate
      limiting rules for the ```docs``` and ```api``` domains.
      The rules are:

      | Rule               | ```docs``` | ```api``` |
      |--------------------|:----------:|:---------:|
      | req / sec / key    | N/A        | 5         |
      | req / sec / IP     | 10         | 10        |
      | connections / key  | N/A        | 25        |
      | connections / IP   | 10         | 5         |
      | max request size   | N/A        | 5K        |

  - title: Performance
    content: |
      In the API docs you'll notice a *Performance Expectations* section for
      endpoint operations. These performance expectations describe the expected
      time to perform the requested operation **after** the request has reached
      the service code which implements the operation. In order to estimate expected
      time to perform an operation from your infrastructure, record the time it
      takes to send repeated requests to the ```/_noop``` endpoint and
      add this ```/_noop``` time to the performance expectation described in the
      API docs.

  - title: Scaling
    content: |
      The ECS runs on a cluster of [CoreOS](https://coreos.com/) machines
      with a layer 5 load balancer running in front of the cluster.
      Each node in the cluster runs the ECS service and schedules tasks
      on that node.
      From an ECS point of view, there are no dependancies between nodes and
      as such the ECS cluster is intended to scale horizontally to accommodate
      a broad variety of workloads.

  - title: Endpoint Documentation Conventions
    content: |
      The remainder of this page contains detailed endpoint documentation.
      There are a few conventions used in the endpoint documentation that
      are worth describing.
      * by default ```ecservice.py``` starts on
        ```http://127.0.0.1:8448``` in a development environment; in the
        endpoint samples you should notice endpoint URLs start with
        the environment varilable ```ECS_ENDPOINT```; the rational here
        is that after setting the ```ECS_ENDPOINT``` environment variable
        you should be able to copy and paste all the sample requests
        regardless of the ip/port on which ```ecservice.py```
        is listening.
      * in the examples you'll see ```-u $ECS_KEY:$ECS_SECRET``` on cURL
        command line; the ```ECS_KEY``` & ```ECS_SECRET``` environment variables refer to
        the authentication key and secret described <a href="#Security">here</a>

/tasks:
  displayName: Tasks
  description: |
    The ```/tasks``` endpoint enables creation and execution of tasks
  post:
    description: |
      Create and execute a task.

      ##### Authentication
        * BASIC authentication using key and secret as described <a href="#Security">here</a>

      ##### Performance Expectations
        * 99% of the time &lt;&nbsp;nnn ms

      ##### Example
      Below is a "hello world" style example of how to run a super simple task
      against a public repo.

      ```bash
      >cat echo.json
      {
        "docker_image": "ubuntu:14.04",
        "cmd": [
          "echo",
          "hello world!!!"
        ]
      }
      >curl \
        -s \
        -u $ECS_KEY:$ECS_SECRET \
        -X POST \
        -H "Content-Type: application/json" \
        --data-binary @echo.json \
        $ECS_ENDPOINT/%ECS_API_VERSION%/tasks | \
        jq
      {
        "stdout": "aGVsbG8gd29ybGQhISEK",
        "stderr": "",
        "exitCode": 0
      }
      >echo ">>>$(echo aGVsbG8gd29ybGQhISEK | base64 --decode)<<<"
      >>>hello world!!!\n<<<
      >
      ```

      The json doc below illustrates how the hello world example request
      payload is modified if the task needs to be run against a private repo.

      ```json
      {
        "docker_image": "ubuntu:14.04",
        "cmd": [
          "echo",
          "hello world!!!"
        ],
        "creds": {
          "username": "something",
          "email": "something@example.com",
          "password": "password"
        }
      }
      ```

    responses:
      200:
        description:
          Success!
      400:
        description:
          Bad request.
      401:
        description:
          Authentication failed.
      404:
        description:
          Docker image not found.
      413:
        description:
          Request body too big.
          Max request size is 5K.
          See <a href="#Request-and-Rate-Limiting">this</a> for details.
      503:
        description:
          You've probably tripped a rate limiting rule.

/_version:
  displayName: Version
  description: |
    The ```/_version``` endpoint reports
    returns the ECS' version.
  get:
    description: |
      The endpoint always returns 200 OK and includes the services'
      version number in the body.

      ##### Authentication
        * BASIC authentication using key and secret as described <a href="#Security">here</a>

      ##### Performance Expectations
        * 99% of the time &lt;&nbsp;50&nbsp;ms

      ##### Example
      ```bash
      >curl -s -u $ECS_KEY:$ECS_SECRET $ECS_ENDPOINT/%ECS_API_VERSION%/_version | jq
      {
        "version": "0.8.0",
        "links": {
          "self": {
            "href": "$ECS_ENDPOINT/%ECS_API_VERSION%/_version"
          }
        }
      }
      >
      ```
    responses:
      200:
        description:
          Assuming authentication is successful, 200 OK is always
          returned by this endpoint.
      401:
        description:
          Authentication failed.
      503:
        description:
          You've probably tripped a rate limiting rule.

/_noop:
  displayName: NoOp
  description: |
    The ```/_noop``` endpoint is intended to be used
    for assessing a deployment's performance.
  get:
    description: |
      The endpoint always returns 200 OK after doing nothing ie. it's a no-op.
      The intended purpose of this endpoint is to measure how long it takes
      for a caller and the service to establish a secure connection
      and complete a request/response roundtrip.

      ##### Authentication
        * BASIC authentication using key and secret as described <a href="#Security">here</a>

      ##### Performance Expectations
        * 99% of the time &lt;&nbsp;50&nbsp;ms

      ##### Example
      ```bash
      >curl \
        -s \
        -u $ECS_KEY:$ECS_SECRET \
        -o /dev/null \
        -w %{http_code}\\n \
        $ECS_ENDPOINT/%ECS_API_VERSION%/_noop
      200
      >
      ```
    responses:
      200:
        description:
          Assuming authentication is successful and you
          don't trip a rate limiting rule,
          200 OK is always returned by this endpoint.
      401:
        description:
          Authentication failed.
      503:
        description:
          You've probably tripped a rate limiting rule.

/_health:
  displayName: Health
  description: |
    An HTTP GET to the ```/_health``` endpoint returns a JSON document
    and HTTP status code which describes the health of the service.
  get:
    description: |
      The JSON document returned by an HTTP GET to the ```/_health```
      endpoint and the HTTP status code describe the health of the service.
      An HTTP status code of 200 OK is healthy and anything else is unhealthy.
      The top level "status" property in the JSON document will be "green" if the service
      is healthy and "red" if there's a problem.
      The "details" property of the JSON document contains a red/green style health entry
      for each of the service's components.
      The overall health is "red" if any of the dependent services are unhealthy.

      Two types of health check are possible. A quick health check
      does not confirm the health of all service components and will
      respond quickly. A comprehensive health check does check
      all service components. The ```quick``` query string parameter
      is a boolean value and used to determine if a quick or comprehensive
      health check is performed.

      ##### Authentication
        * BASIC authentication using key and secret as described <a href="#Security">here</a>

      ##### Usage Expectations
        * external monitoring service will perform a quick health check every minute
        * external monitoring service will perform a comprehensive health check 5 minutes

      ##### Performance Expectations
        * quick - 99% of the time &lt;&nbsp;50&nbsp;ms
        * comprehensive - 99% of the time &lt;&nbsp;nnn ms

      ##### Example
      Below is a sample of a healthy response to a request
      for a comprehensive health check.

      ```bash
      >curl \
        -s \
        -u $ECS_KEY:$ECS_SECRET \
        $ECS_ENDPOINT/%ECS_API_VERSION%/_health?quick=false | \
        jq
      {
        "status": "green",
        "details": {
          "docker remote api": {
            "status": "green",
            "details": {
              "connectivity": "green",
              "api version": "green"
            }
          }
        },
        "links": {
          "self": {
            "href": "$ECS_ENDPOINT/%ECS_API_VERSION%/_health"
          }
        }
      }
      >
      ```

    queryParameters:
      quick:
        displayName: quick
        type: boolean
        description:
          Determines if a quick or comprehensive health check is performed.
          If ```quick``` does not appear in the query string a quick health
          check is performed.
        example: true
        required: false
    responses:
      200:
        description:
          When everything is green a 200 OK is returned.
      401:
        description:
          Authentication failed.
      500:
        description:
          something super nasty happened inside the service
      503:
        description:
          When something is red a 503 service unavailable is returned
          or you've tripped a rate limiting rule.
